
configfile: "config/config.yaml"

SAMPLES = config["samples"]

genome = config["reference_genome"]


rule all:
    input:
        expand("results/vcf/{sample}.filtered.vcf", sample=SAMPLES),
        expand("results/mapped/{sample}.sorted.bam.flagstat", sample=SAMPLES),
        expand("results/mapped/{sample}.sorted.bam.idxstats", sample=SAMPLES)


include: "rules/preprocess.smk"
include: "rules/aligning.smk"
include: "rules/calling.smk"
